config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :prospects
  get "up" => "rails/health#show", as: :rails_health_check
  root "prospects#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # Guest user (not logged in)

    if user.persisted? # Check if the user is logged in
      can :manage, :all
    end
    # No additional abilities for guests
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/prospect.rb
class Prospect < ApplicationRecord

  validates :industry,presence: true
  validates :jobrole,presence: true
  belongs_to :user

  enum industry: { industry_high: 'high', industry_medium: 'medium', industry_low: 'low' }
  enum jobrole: { jobrole_high: 'high', jobrole_medium: 'medium', jobrole_low: 'low' }
  enum designer: { designer_high: 'high', designer_medium: 'medium', designer_low: 'low' }
  enum location: { location_high: 'high', location_medium: 'medium', location_low: 'low' }
  after_create_commit {broadcast_append_to "prospects"}
  after_update_commit {broadcast_replace_to "prospects"}
  after_destroy_commit {broadcast_remove_to "prospects"}

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :prospects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/prospects_controller.rb
class ProspectsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource
  before_action :set_prospect, only: %i[ show edit update destroy ]


  # GET /prospects or /prospects.json
  def index
    @prospects = Prospect.all
    @prospect = Prospect.new
  end

  # GET /prospects/1 or /prospects/1.json
  def show
  end

  # GET /prospects/new
  def new
    @prospect = current_user.prospects.build
  end

  # GET /prospects/1/edit
  def edit
  end

  # POST /prospects or /prospects.json
  def create
    @prospect = current_user.prospects.build(prospect_params)

    respond_to do |format|
      if @prospect.save
        format.html { redirect_to prospects_url, notice: "Prospect was successfully created." }
        format.json { render :show, status: :created, location: @prospect }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /prospects/1 or /prospects/1.json
  def update
    respond_to do |format|
      if @prospect.update(prospect_params)
        format.html { redirect_to prospects_url, notice: "Prospect was successfully updated." }
        format.json { render :show, status: :ok, location: @prospect }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @prospect.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /prospects/1 or /prospects/1.json
  def destroy
    @prospect.destroy!

    respond_to do |format|
      format.html { redirect_to prospects_url, notice: "Prospect was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_prospect
      @prospect = Prospect.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def prospect_params
      params.require(:prospect).permit(:industry, :jobrole, :designer, :location)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/prospects_helper.rb
module ProspectsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html style="<%= polaris_html_styles %>">
<head>
  <title>ProjectApp</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag "polaris_view_components" %>
  <%= javascript_importmap_tags %>

  <% if user_signed_in? %>
    <div class="Polaris-Banner Polaris-Banner--statusSuccess Polaris-Banner--withinPage">
      <div class="Polaris-Banner__ContentWrapper">
        <div class="Polaris-Banner__Content">
            <span role="img" aria-label="Farrah" class="Polaris-Avatar Polaris-Avatar--sizeMedium Polaris-Avatar--shapeRound" style="background-color: #008C00;">
              <img src="https://www.redditstatic.com/desktop2x/img/favicon/apple-icon-180x180.png" class="Polaris-Avatar__Image" role="presentation" onerror="this.src=''" />
            </span>
          <div class="Polaris-Text--root Polaris-Text--subdued Polaris-Text--block" style="margin-left: 8px;">
            Welcome <%= current_user.email %>
          </div>
        </div>
        <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "Polaris-Banner__DismissButton" %>
      </div>
    </div>
  <% else %>
    <div class="Polaris-Banner Polaris-Banner--statusCritical Polaris-Banner--withinPage">
      <div class="Polaris-Banner__ContentWrapper">
        <h2 class="Polaris-Text--root Polaris-Text--headingMd Polaris-Text--semibold Polaris-Text--break">
          Sign Up to Continue
        </h2>
        <div class="Polaris-Box">
          <div class="Polaris-Box">
            <div class="Polaris-ButtonGroup">
              <div class="Polaris-ButtonGroup__Item">
                <div class="Polaris-Box">
                  <%= button_to "Sign in", new_user_session_path, class: "Polaris-Button" %>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
</head>

<body style="<%= polaris_body_styles %>">
<%= yield %>
</body>
</html>

app/views/prospects/_form.html.erb
<div class="Polaris-LegacyCard">
  <div class="Polaris-CalloutCard__Container">
    <div class="Polaris-LegacyCard__Section">
      <div class="Polaris-CalloutCard">
        <div class="Polaris-CalloutCard__Content">
          <div class="Polaris-CalloutCard__Title">
            <h2 class="Polaris-Text--root Polaris-Text--headingMd Polaris-Text--semibold">
<%= form_with(model: prospect) do |form| %>
  <% if prospect.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(prospect.errors.count, "error") %> prohibited this prospect from being saved:</h2>

      <ul>
        <% prospect.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :industry, style: "display: block" %>
    <%= form.select :industry, Prospect.industries.keys, prompt: 'Select Industry' %>
  </div>

  <div>
    <%= form.label :jobrole, style: "display: block" %>
    <%= form.select :jobrole, Prospect.jobroles.keys, prompt: 'Select Job Role' %>
  </div>

  <div>
    <%= form.label :designer, style: "display: block" %>
    <%= form.select :designer, Prospect.designers.keys, prompt: 'Select Designer' %>
  </div>

  <div>
    <%= form.label :location, style: "display: block" %>
    <%= form.select :location, Prospect.locations.keys, prompt: 'Select Location' %>
  </div>

  <%= turbo_frame_tag "partialform" do %>
    <div>
      <%= form.submit %>

    </div>
                  <img class="Polaris-CalloutCard__Image" src="https://cdn.shopify.com/s/assets/admin/checkout/settings-customizecart-705f57c725ac05be5a34ec20c05b94298cb8afd10aac7bd9c7ad02030f48cfa0.svg" alt="">

            <% end %>
<% end %>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prospects/_prospect.html.erb
<div class="Polaris-LegacyCard">
  <div class="Polaris-CalloutCard__Container">
    <div class="Polaris-LegacyCard__Section">
      <div class="Polaris-CalloutCard">
        <div class="Polaris-CalloutCard__Content">
          <div class="Polaris-CalloutCard__Title">
            <h2 class="Polaris-Text--root Polaris-Text--headingMd Polaris-Text--semibold">
<div id="<%= dom_id prospect %>">
  <p>
    <strong>Industry:</strong>
    <%= prospect.industry %>
  </p>

  <p>
    <strong>Jobrole:</strong>
    <%= prospect.jobrole %>
  </p>

  <p>
    <strong>Designer:</strong>
    <%= prospect.designer %>
  </p>

  <p>
    <strong>Location:</strong>
    <%= prospect.location %>
  </p>

</div>
            </h2>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/prospects/edit.html.erb
<%= turbo_frame_tag "editprospect" do %>

  <h1>Editing prospect</h1>

<%= render "form", prospect: @prospect %>

<br>

<div>
  <%= link_to "Back to prospects", @prospects %>
</div>
<%end %>

app/views/prospects/index.html.erb
<p style="color: green"><%= notice %></p>

<p style="color: green"><%= notice %></p>
<div class="Polaris-LegacyCard">
  <div class="Polaris-LegacyCard__Header">
    <h2 class="Polaris-Text--root Polaris-Text--headingMd Polaris-Text--semibold">
      <p class="Polaris-Text--root Polaris-Text--heading2xl Polaris-Text--semibold">
        Prospects
      </p>
    </h2>
  </div>
</div>

<%= turbo_stream_from "prospects" %>

<div id="prospects">
  <% @prospects.each do |prospect| %>
    <%= render prospect %>
    <p>

      <%= turbo_frame_tag "_top" do %>

        <%= link_to "Show this prospect", prospect, data: { turbo_frame: "_top" },class: "Polaris-Button Polaris-Button--primary"  %>
      <%end %>
        <%= turbo_frame_tag "editprospect" do %>
      <%= link_to "Edit this prospect", edit_prospect_path(prospect), class: "Polaris-Button Polaris-Button--destructive" %>
        <%end %>
      <%= button_to "Destroy this project", prospect, method: :delete,class: "Polaris-Button Polaris-Button--destructive" %>


    </p>
  <% end %>
</div>

<%= turbo_frame_tag "newprospect" do %>
<%= link_to "New prospect", new_prospect_path,class: "Polaris-Button Polaris-Button--primary" %>
<%end %>

app/views/prospects/new.html.erb
<%= turbo_frame_tag "newprospect" do %>
  <h1>New prospect</h1>

<%= render "form", prospect: @prospect %>

<br>

<div>
  <%= link_to "Back to prospects", (@prospects) %>
</div>
<%end %>

app/views/prospects/show.html.erb
<p style="color: green"><%= notice %></p>
<%= turbo_frame_tag "top" do %>
<%= render @prospect %>
<div>
  <%= link_to "Back to prospects",prospects_path( @prospects) %>
</div>
<%end %>